import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import styles from './layout.module.css';
import Footer from "@/components/Footer";
import Logo from '@/assets/img/logo.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  title
}: Readonly<{
  children: React.ReactNode;
  title: string
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <Navbar />
          <div className="block md:hidden mt-5 text-center">
            {Logo && (
              <Image
                src={Logo}
                alt="rixusart-cat"
                width={270}
                height={36}
                className="object-cover object-center"
              />
            )}
          </div>
          <main id={styles.contentWrapper}>
            {title && (
              <div className="bg-zinc-50 h-16 md:h-24 flex flex-col justify-center items-center mt-5 md:mt-0">
                <h1 className="text-4xl md:text-5xl font-semibold">{title}</h1>
              </div>
            )}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
